name: Build

on:
  push:
  pull_request:

jobs:
  # run build in monorepo
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2

      - name: Install deps
        run: pnpm install

      - name: Run build in every package
        run: pnpm -r build
